plugins:
  eslint:
    enabled: true
    config:
      config: .eslintrc.js
  duplication:
    enabled: true
    config:
      languages:
      - javascript
    exclude_patterns:
    - "test/**"
exclude_patterns:
- "node_modules/**"
checks:
  method-lines:
    enabled: false
