jobs:
  build:
    docker:
      -
        image: "circleci/node:latest"
      -
        environment:
          POSTGRES_DB: drb_test
          POSTGRES_PASSWORD: ""
          POSTGRES_USER: postgres
        image: "circleci/postgres:9.6.2-alpine"
    steps:
      - checkout
      -
        restore_cache:
          keys:
            - "v1-dependencies-{{ checksum \"package.json\" }}"
            - v1-dependencies-
      -
        run: "npm install"
        jobs:
  build:
    docker:
      -
        image: "circleci/node:latest"
      -
        environment:
          POSTGRES_DB: drb_test
          POSTGRES_PASSWORD: ""
          POSTGRES_USER: postgres
        image: "circleci/postgres:9.6.2-alpine"
    steps:
      - checkout
      -
        restore_cache:
          keys:
            - "v1-dependencies-{{ checksum \"package.json\" }}"
            - v1-dependencies-
      -
        run: "npm install"
      
        run: "cp ~/repo/api/.keys.json ~/repo/api/keys.json"
      -
        run: "npm run db_init"
      -
        run: "npm run test"
      -
        save_cache:
          key: "v1-dependencies-{{ checksum \"package.json\" }}"
          paths:
            - node_modules
    working_directory: ~/repo
version: 2
