version: 2
jobs:
  build:
    parallelism: 3
    working_directory: ~/repo
    docker:
      - image: "circleci/node:latest"
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: drb_test
          POSTGRES_PASSWORD: ""
      - image: "circleci/postgres:9.6.2-alpine"
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: drb_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - restore_cache:
          keys:
            - "v1-dependencies-{{ checksum \"package.json\" }}"
            - v1-dependencies-
      - run: "npm install"
      - run: "cp ~/repo/api/.keys.json ~/repo/api/keys.json"
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      -
        run: "npm run db_init"
      -
        run: "npm run test"
      - save_cache:
          key: "v1-dependencies-{{ checksum \"package.json\" }}"
          paths:
            - node_modules
